language: php

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - >
    if [[ "$TYPO3" = *"dev"* ]]; then
      composer config minimum-stability dev;
      composer config prefer-stable true;
      composer require typo3/cms-core="@dev" --no-update;
    fi
  - composer require nimut/typo3-complete:$TYPO3
  - mkdir -p .Build/public/typo3conf/ext/
  - if [ ! -L .Build/public/typo3conf/ext/my_skeleton ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/my_skeleton; fi
  - export TYPO3_PATH_ROOT=$PWD/.Build/public
  - export typo3DatabaseName=typo3
  - export typo3DatabaseHost=localhost
  - export typo3DatabaseUsername=root
  - export typo3DatabasePassword=

script:
  - >
    if [ -d "Tests/Unit" ]; then
      echo;
      echo "Running unit tests";
      echo;
      echo;
      .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/;
    fi

  - >
    if [ -d "Tests/Functional" ]; then
      echo;
      echo "Running functional tests";
      echo;
      echo;
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';
    fi

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.2
      env: TYPO3=dev-master
    - stage: test
      php: 7.2
      env: TYPO3=^9.0
    - stage: test
      php: 7.1
      env: TYPO3=^8.7
    - stage: test
      php: 7.0
      env: TYPO3=^8.7
    - stage: test
      php: 5.6
      env: TYPO3=^7.6
    - stage: test
      php: 5.5
      env: TYPO3=^7.6

    - stage: 🚢 to ter
      if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
      php: 7.0
      env: TYPO3=^8.7
      before_install: skip
      install: skip
      before_script: skip
      script:
      - >
        echo;
        echo "Preparing upload of release ${TRAVIS_TAG} to TER";
        echo;
        echo;
        composer require --dev nimut/typo3-complete:$TYPO3;
        composer require --update-no-dev helhum/ter-client:dev-master;

        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx;

        # Upload
        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
        echo;
        echo "Uploading release ${TRAVIS_TAG} to TER";
        echo;
        echo;
        .Build/bin/ter-client upload my_skeleton . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";
